### ISSUE TITLE
Add BUILD_EXCLUSIVE_KERNEL to dkms.conf of various kernel specific branches

### ISSUE THREAD

**Issue by crass** [toby63/shiftfs-dkms#10]
Adding the `BUILD_EXCLUSIVE_KERNEL` variable will tell dkms to only build the module for supported kernels. For instance, I added `BUILD_EXCLUSIVE_KERNEL="^5.13.*"` for the k513 branch because have this module installed in `/usr/src` so that it will be built every time I upgrade my kernel. I ran in to some file corruption and ended up needing to reinstall kernel headers for multiple kernels, which triggered a rebuilt for all dkms modules against all kernels which had headers reinstalled. Without the `BUILD_EXCLUSIVE_KERNEL` variable dkms would try to built the shiftfs-k513 against all the kernels, eg. 5.11 and 5.10, and would cause an error with non-5.13 kernels. This fixes that issue.

---

Todo:

Try and implement `BUILD_EXCLUSIVE_KERNEL`
- [x] for multiple branches, e.g. `^5.(10|8).*`:
    - [x] 5.10 (5.8 to 5.10)
    - [x] 5.4 (5.4 and <5.8)
- [x] in AUR packages
- [x] in 5.13
- [ ] (optional) Test scenario with mutiple shiftfs versions installed at the same time
- [x] (optional) change 5.13 for multiple branches (once 5.14 is available)
- [x] (optional) change AUR packages for multiple branches

**Comment by toby63** [comment]
That is a good idea.
I haven't really thought about this possibility, but you are right, if you install different kernel branches this can be a problem.

One question:
Did you try to install multiple versions of the shiftfs module and does that also work with your method?

**Comment by toby63** [comment]
Fixed for [k5.13](https://github.com/toby63/shiftfs-dkms/tree/k5.13).

**Comment by toby63** [comment]
Implemented.
