### ISSUE TITLE
k5.8 branch renamed to k5.10

### ISSUE THREAD

**Issue by lox** [toby63/shiftfs-dkms#13]
**Question:**

Looks like the k5.8 branch was renamed to k5.10, can I use the k5.10 branch for Ubuntu 20.04 which has a 5.8 kernel?

**Comment by toby63** [comment]
@lox 
1. shiftfs should already be included in the regular Ubuntu kernel.
2. For now you can still use it.

**Comment by toby63** [comment]
I have decided to mention 5.8 as well.
