### ISSUE TITLE
Feature Request: Support for Kernel versions 5.17 and 5.18

### ISSUE THREAD

**Issue by aledbf** [toby63/shiftfs-dkms#18]
Thanks!

**Comment by toby63** [comment]
I might take a look at it in the coming days.

Upstream has indeed a new version available for 5.17, see [ubuntu kernel repo](https://git.launchpad.net/~ubuntu-kernel/ubuntu/+source/linux/+git/jammy/log/fs/shiftfs.c?h=hwe-5.17).
I don't know whether it also works for 5.18, but you could give it a try.

In case you want to try the new version before I upload new scripts, follow these steps:
**Note: Use at your own risk.**

1. Remove the old version (see [Readme](https://github.com/toby63/shiftfs-dkms/tree/k5.16#uninstallremove) for example).
2. Download the scripts for 5.16 (see Step 1 in [Readme](https://github.com/toby63/shiftfs-dkms/tree/k5.16#1-download-this-repo)).
3. Replace the `shiftfs.c` file with the one [here](https://git.launchpad.net/~ubuntu-kernel/ubuntu/+source/linux/+git/jammy/plain/fs/shiftfs.c?h=hwe-5.17&id=dab801bab38fe568f12f79eacf10362b9c9e25f9), you can simply run:
    - `rm shiftfs.c`
    - `wget 'https://git.launchpad.net/~ubuntu-kernel/ubuntu/+source/linux/+git/jammy/plain/fs/shiftfs.c?h=hwe-5.17&id=dab801bab38fe568f12f79eacf10362b9c9e25f9'`
    -  `mv 'shiftfs.c?h=hwe-5.17&id=dab801bab38fe568f12f79eacf10362b9c9e25f9' shiftfs.c`
4. Adjust the `version.txt` file to `k517`.
5. Change the following line in `dkms.conf`: `BUILD_EXCLUSIVE_KERNEL="^5.(15|16).*"` to `BUILD_EXCLUSIVE_KERNEL="^5.(17|18).*"`.
6. Compile and install shiftfs (see Step 3 in [Readme](https://github.com/toby63/shiftfs-dkms/tree/k5.16#3-compile-and-install-shiftfs-with-dkms)).

**Comment by toby63** [comment]
Closed by ef6f72a12389c416038f2cbb2db8c429dc5aaaa4.
