### ISSUE TITLE
Regex issue in dkms.conf for BUILD_EXCLUSIVE

### ISSUE THREAD

**Issue by rangamani54** [toby63/shiftfs-dkms#26]
**Description of the Bug/Problem: Error! The /var/lib/dkms/shiftfs/k518/5.19.0-1025-aws/x86_64/dkms.conf for module shiftfs includes a BUILD_EXCLUSIVE directive which does not match this kernel/arch.**

**How to Reproduce:**
1. Go to 'shifts repo'
2. Then, run the command `sudo make -f Makefile.dkms ` as given in the installation process.
3. While it is trying to build, it got failed.
`mkdir -p '/usr/src/shiftfs-k518'
cp Makefile shiftfs.c '/usr/src/shiftfs-k518'
sed 's/#MODULE_VERSION#/k518/' dkms.conf > '/usr/src/shiftfs-k518/dkms.conf'
dkms build -m shiftfs -v k518
Error! The /var/lib/dkms/shiftfs/k518/5.19.0-1025-aws/x86_64/dkms.conf for module shiftfs includes a BUILD_EXCLUSIVE directive which does not match this kernel/arch.
This indicates that it should not be built.
make: *** [Makefile.dkms:16: build] Error 9`

**I tried changing the regex expression from BUILD_EXCLUSIVE_KERNEL="^(5\.[18-19]+\.|6\.0\.)" to BUILD_EXCLUSIVE_KERNEL="^(5\.[18,19]+\.|6\.0\.)" in dkms.conf file. Then, it has been installed.**

**System information:**
* OS/Distribution: Ubuntu
* Kernelversion: 5.19
* shiftfs-dkms-version: k518

****

**Comment by toby63** [comment]
Interesting, thx for the report.

It seems I haven't tested this properly, so sry.
I will try to do some tests tomorrow.

If it works for you now, I guess that other users can find this report in the meantime.

**Comment by toby63** [comment]
Fixed with https://github.com/toby63/shiftfs-dkms/commit/e5c16cbd3d91378ba67a148f704581febb981036 .

I hope it works now, otherwise report again.
